# ------------------------------------------------------------------------------
# docker-compose.yml
# ------------------------------------------------------------------------------

# This repository's project Docker Compose file. This is limited to required
# extensions/overrides of Docker Composer services defined by the Docker Compose
# files in the gimp and npm tools, included here as submodules.

---

services:

   ansible:

   ansible-playbook:
