# ------------------------------------------------------------------------------
# inventory/host_vars/prod5/public.yml
# ------------------------------------------------------------------------------

---

wp_sites:

  friends:

    admin_password: "{{ priv_wp_sites.friends.admin_password }}"
    database_password: "{{ priv_wp_sites.friends.database_password }}"

    reverse_proxy_pass_port: 8080

    plugins: []

    themes: []

    config: |-
      // reCAPTCHA site key
      define(
          'VL_RECAPTCHA_SITE_KEY',
          '6LdG0RAtAAAAANXenwaqR2gooFp0bq3S1VBAFVsL'
      );
      define(
          'VL_RECAPTCHA_SECRET_KEY',
          '{{ priv_wp_sites.friends.recaptcha_secret_key }}'
      );

  redesign:

    admin_password: "{{ priv_wp_sites.redesign.admin_password }}"
    database_password: "{{ priv_wp_sites.redesign.database_password }}"

    reverse_proxy_pass_port: 8085

    plugins: []

    themes: []

  www:

    admin_password: "{{ priv_wp_sites.www.admin_password }}"
    database_password: "{{ priv_wp_sites.www.database_password }}"

    reverse_proxy_pass_port: 8086

    plugins: []

    themes: []

    config: "{{ priv_wp_sites.www.config }}"
